=== Dmitry1271/JWD_Task04-parsing/xml-parsing/target/classes/flowers/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.tc.com/flowers"
        xmlns:tns="http://www.epam.tc.com/flowers">

    <element name="flowers">
        <complexType>
            <sequence>
                <element name="flower" type="tns:Flower" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Flower">
        <sequence>
            <element name="name" type="string"/>
            <element name="soil" type="tns:Soil"/>
            <element name="origin" type="string"/>
            <element name="growing-tips" type="tns:Growing-tips"/>
            <element name="multiplying" type="tns:Multiplying"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="stem-color" type="string" use="optional"/>
        <attribute name="leaves-color" type="string" use="optional"/>
        <attribute name="average-size" type="positiveInteger" use="optional"/>
    </complexType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="ground"/>
            <enumeration value="sod-podzolic"/>
        </restriction>
    </simpleType>

    <complexType name="Growing-tips">
        <sequence>
            <element name="temperature">
                <simpleType>
                    <restriction base="string">
                        <pattern value="(0 cel)|(-[1-9][0-9]? cel)|(\+[1-9][0-9]? cel)"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="lighting" type="boolean"/>
            <element name="watering">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[1-9][0-9]{0,5} per/week"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leavers"/>
            <enumeration value="cuttings"/>
            <enumeration value="seeds"/>
        </restriction>
    </simpleType>

</schema>

=== Dmitry1271/JWD_Task04-parsing/xml-parsing/target/xml-parsing/WEB-INF/classes/flowers/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flow:flowers xmlns:flow="http://www.epam.tc.com/flowers"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.epam.tc.com/flowers flowers.xsd">

    <flower id="flower1" stem-color="green">
        <name>rose</name>
        <soil>ground</soil>
        <origin>Italy</origin>
        <growing-tips>
            <temperature>+27 cel</temperature>
            <lighting>true</lighting>
            <watering>5000 per/week</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </flower>

    <flower id="flower2" leaves-color="yellow" stem-color="green">
        <name>dandelion</name>
        <soil>podzolic</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower3" leaves-color="white" stem-color="green">
        <name>chamomile</name>
        <soil>sod-podzolic</soil>
        <origin>garden</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower4" leaves-color="white">
        <name>eustoma</name>
        <soil>ground</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower5" stem-color="green">
        <name>loosestrife</name>
        <soil>podzolic</soil>
        <origin>garden</origin>
        <growing-tips>
            <temperature>+28 cel</temperature>
            <lighting>true</lighting>
            <watering>4500 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower6">
        <name>aster</name>
        <soil>ground</soil>
        <origin>Russia</origin>
        <growing-tips>
            <temperature>+23 cel</temperature>
            <lighting>true</lighting>
            <watering>5000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower7" stem-color="green">
        <name>tulp</name>
        <soil>podzolic</soil>
        <origin>Ukraine</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>5000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower8" leaves-color="purple" stem-color="purple">
        <name>cedar-case</name>
        <soil>sod-podzolic</soil>
        <origin>room</origin>
        <growing-tips>
            <temperature>+27 cel</temperature>
            <lighting>true</lighting>
            <watering>3500 per/week</watering>
        </growing-tips>
        <multiplying>leavers</multiplying>
    </flower>

    <flower id="flower9" leaves-color="red" stem-color="red">
        <name>begonia</name>
        <soil>ground</soil>
        <origin>room</origin>
        <growing-tips>
            <temperature>+28 cel</temperature>
            <lighting>true</lighting>
            <watering>4500 per/week</watering>
        </growing-tips>
        <multiplying>leavers</multiplying>
    </flower>

    <flower id="flower10" leaves-color="green" stem-color="green">
        <name>aloe</name>
        <soil>ground</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+27 cel</temperature>
            <lighting>true</lighting>
            <watering>1000 per/week</watering>
        </growing-tips>
        <multiplying>leavers</multiplying>
    </flower>

    <flower id="flower11">
        <name>chrysanthemum</name>
        <soil>podzolic</soil>
        <origin>garden</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower12" leaves-color="green">
        <name>aglaonema</name>
        <soil>sod-podzolic</soil>
        <origin>Russia</origin>
        <growing-tips>
            <temperature>+22 cel</temperature>
            <lighting>false</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </flower>

    <flower id="flower13" leaves-color="green">
        <name>sansevieria</name>
        <soil>podzolic</soil>
        <origin>USA</origin>
        <growing-tips>
            <temperature>+31 cel</temperature>
            <lighting>false</lighting>
            <watering>3400 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower14" stem-color="green">
        <name>cactus</name>
        <soil>podzolic</soil>
        <origin>China</origin>
        <growing-tips>
            <temperature>+38 cel</temperature>
            <lighting>true</lighting>
            <watering>100 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower15" leaves-color="green" stem-color="green">
        <name>philodendron</name>
        <soil>podzolic</soil>
        <origin>home</origin>
        <growing-tips>
            <temperature>+22 cel</temperature>
            <lighting>false</lighting>
            <watering>3000 per/week</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </flower>

    <flower id="flower16" stem-color="green">
        <name>sage</name>
        <soil>sod-podzolic</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+24 cel</temperature>
            <lighting>true</lighting>
            <watering>2500 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower17" stem-color="green">
        <name>rose</name>
        <soil>ground</soil>
        <origin>Italy</origin>
        <growing-tips>
            <temperature>+27 cel</temperature>
            <lighting>true</lighting>
            <watering>5000 per/week</watering>
        </growing-tips>
        <multiplying>cuttings</multiplying>
    </flower>

    <flower id="flower18" leaves-color="yellow" stem-color="green">
        <name>dandelion</name>
        <soil>podzolic</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower19" leaves-color="white" stem-color="green">
        <name>chamomile</name>
        <soil>sod-podzolic</soil>
        <origin>garden</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower20" leaves-color="white">
        <name>eustoma</name>
        <soil>ground</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>4000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower21" stem-color="green">
        <name>loosestrife</name>
        <soil>podzolic</soil>
        <origin>garden</origin>
        <growing-tips>
            <temperature>+28 cel</temperature>
            <lighting>true</lighting>
            <watering>4500 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower22">
        <name>aster</name>
        <soil>ground</soil>
        <origin>Russia</origin>
        <growing-tips>
            <temperature>+23 cel</temperature>
            <lighting>true</lighting>
            <watering>5000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower23" stem-color="green">
        <name>tulp</name>
        <soil>podzolic</soil>
        <origin>Ukraine</origin>
        <growing-tips>
            <temperature>+25 cel</temperature>
            <lighting>true</lighting>
            <watering>5000 per/week</watering>
        </growing-tips>
        <multiplying>seeds</multiplying>
    </flower>

    <flower id="flower24" leaves-color="purple" stem-color="purple">
        <name>cedar-case</name>
        <soil>sod-podzolic</soil>
        <origin>room</origin>
        <growing-tips>
            <temperature>+27 cel</temperature>
            <lighting>true</lighting>
            <watering>3500 per/week</watering>
        </growing-tips>
        <multiplying>leavers</multiplying>
    </flower>

    <flower id="flower25" leaves-color="red" stem-color="red">
        <name>begonia</name>
        <soil>ground</soil>
        <origin>room</origin>
        <growing-tips>
            <temperature>+28 cel</temperature>
            <lighting>true</lighting>
            <watering>4500 per/week</watering>
        </growing-tips>
        <multiplying>leavers</multiplying>
    </flower>

    <flower id="flower26" leaves-color="green" stem-color="green">
        <name>aloe</name>
        <soil>ground</soil>
        <origin>Belarus</origin>
        <growing-tips>
            <temperature>+27 cel</temperature>
            <lighting>true</lighting>
